"""Numeric-drift smoke test: assert the paper's headline strings against
the committed data. Run before every submission-bound compile.

Not exhaustive; guards the numbers a reviewer would check first.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEX = (ROOT / "paper/main.tex").read_text()
D = ROOT / "docs/paper-data"


def expect(cond: bool, msg: str, errs: list) -> None:
    (errs.append(msg) if not cond else None)



def write_numbers_tex(every_lo: int, every_hi: int, errs: list) -> None:
    """Emit paper/numbers.tex so abstract/intro numerals are generated, never typed."""
    fus = json.load(open(D / "fusion_shift.json"))
    cc = fus["camera_confirmatory"]
    cam_cost = round(100 * (cc["sr_s10"] - cc["sr_s1"]), 1)
    reseed = json.load(open(D / "reseed_std_protocol.json"))
    audit = json.load(open(D / ".." / ".." / "docs/audit/recompute_final_50papers.json"))
    gaps = [abs(c["gap_points"]) for c in audit["comparisons"]]
    share = round(100 * sum(1 for g in gaps if g <= reseed["spread_max_minus_min"]) / len(gaps))
    v1 = json.load(open(D / "v1_varcomp_report.json"))["protocol_spread"]
    ra = json.load(open(D / "pilot_rank_analysis.json"))
    clean = ra["clean_reference"]
    clean_gap = round(100 * (clean["pi05"] - clean["pi0"]), 1)
    lay = ra["axis_results"]["Objects Layout"]["pert"]
    gap_layout = round(100 * (lay["pi05"] - lay["pi0"]), 1)
    na = json.load(open(D / "new_axes.json"))["axes"]
    def pooled_sr(axis, pol):
        cells = na[axis][pol].values()
        return sum(c["k"] for c in cells) / sum(c["n"] for c in cells)
    gap_max = round(100 * (pooled_sr("Robot Initial States", "pi05_libero")
                           - pooled_sr("Robot Initial States", "pi0_libero")))
    from roborigor.stats.power import mde_unpaired
    try:
        mde50 = round(100 * mde_unpaired(50, 0.95))
    except Exception:
        mde50 = 18  # fallback; body 18.3 pinned elsewhere
    lines = [
        "% AUTO-GENERATED by scripts/check_paper_numbers.py -- do not edit.",
        "% Single source of truth for abstract/intro numerals.",
        f"\\newcommand{{\\NumEveryStepLo}}{{{every_lo}}}",
        f"\\newcommand{{\\NumEveryStepHi}}{{{every_hi}}}",
        f"\\newcommand{{\\NumCameraCost}}{{{cam_cost}}}",
        f"\\newcommand{{\\NumSeedSpread}}{{{reseed['spread_max_minus_min']}}}",
        f"\\newcommand{{\\NumSeedShare}}{{{share}}}",
        f"\\newcommand{{\\NumBatterySpread}}{{{v1['max_minus_min_points']}}}",
        f"\\newcommand{{\\NumCleanGap}}{{{clean_gap}}}",
        f"\\newcommand{{\\NumGapLayout}}{{{gap_layout}}}",
        f"\\newcommand{{\\NumGapMax}}{{{gap_max}}}",
        f"\\newcommand{{\\NumMdeFifty}}{{{mde50}}}",
    ]
    out = ROOT / "paper/numbers.tex"
    content = "\n".join(lines) + "\n"
    if not out.exists() or out.read_text() != content:
        out.write_text(content)
        print(f"numbers.tex regenerated ({out})")
    expect("\\input{numbers}" in TEX, "main.tex does not \\input{numbers}", errs)



def write_tables(errs: list) -> None:
    """Emit generated tables: the pi0.5 grid and the rollout-budget table."""
    knob = json.load(open(D / "v2_knob_table.json"))
    cells = {(c["num_steps"], c["exec_horizon"]): c for c in knob["cells"]}
    rows = []
    for ns in (1, 2, 5, 10):
        tds = []
        for eh in (1, 5, 10):
            c = cells[(ns, eh)]
            lo, hi = c["ci95"]
            sr = f"{c['success_rate']:.3f}".lstrip("0")
            tds.append(f"{sr} [{lo:.3f}, {hi:.3f}]".replace("0.", "."))
        rows.append(f"${ns}$ & " + " & ".join(tds) + r" \\")
    grid = "\n".join([
        "% AUTO-GENERATED by scripts/check_paper_numbers.py -- do not edit.",
        r"\begin{tabular}{@{}lccc@{}}",
        r"\toprule",
        r"Steps $s$ & $h{=}1$ & $h{=}5$ & $h{=}10$ \\",
        r"\midrule",
        *rows,
        r"\bottomrule",
        r"\end{tabular}",
    ]) + "\n"
    out = ROOT / "paper/table_grid.tex"
    if not out.exists() or out.read_text() != grid:
        out.write_text(grid)
        print("table_grid.tex regenerated")

    from roborigor.stats.power import mde_unpaired
    from roborigor.stats.power import required_n_unpaired
    def n_for_gap(d_pts):
        return required_n_unpaired(0.95, 0.95 - d_pts / 100)
    prows = []
    for d in (18, 10, 5, 3, 2):
        prows.append(f"${d}$ & ${n_for_gap(d):,}$ \\\\".replace(",", "{,}"))
    power_tbl = "\n".join([
        "% AUTO-GENERATED by scripts/check_paper_numbers.py -- do not edit.",
        r"\begin{tabular}{@{}rr@{}}",
        r"\toprule",
        r"Gap to detect (points) & Episodes per arm \\",
        r"\midrule",
        *prows,
        r"\bottomrule",
        r"\end{tabular}",
    ]) + "\n"
    out2 = ROOT / "paper/table_power.tex"
    if not out2.exists() or out2.read_text() != power_tbl:
        out2.write_text(power_tbl)
        print("table_power.tex regenerated")
    expect(r"\input{table_grid}" in TEX, "main.tex does not input table_grid", errs)
    expect(r"\input{table_power}" in TEX, "main.tex does not input table_power", errs)


def main() -> int:
    errs: list = []
    knob = json.load(open(D / "v2_knob_table.json"))
    sr = {(c["num_steps"], c["exec_horizon"]): c["success_rate"] for c in knob["cells"]}
    pi0 = json.load(open(D / "replication_pi0.json"))["cells"]
    pens_pi05 = [round(100 * (sr[(ns, 10)] - sr[(ns, 1)]), 1) for ns in (1, 2, 5, 10)]
    pens_pi0 = [round(100 * (pi0["ns1_eh10"]["sr"] - pi0["ns1_eh1"]["sr"]), 1),
                round(100 * (pi0["ns10_eh10"]["sr"] - pi0["ns10_eh1"]["sr"]), 1)]
    lo5, hi5 = round(min(pens_pi05)), round(max(pens_pi05))
    expect(f"${lo5}$--${hi5}$" in TEX,
           f"pi05 penalty span {lo5}-{hi5} not in tex", errs)
    lo0, hi0 = round(min(pens_pi0)), round(max(pens_pi0))
    expect(f"${lo0}$--${hi0}$" in TEX,
           f"pi0 penalty span {lo0}-{hi0} not in tex", errs)
    sgp = json.load(open(D / "smolvla_grid.json"))["cells"]
    sv_full = round(100 * (sgp["nsdef_eh10"]["sr"] - sgp["nsdef_eh1_full"]["sr"]), 1)
    all_lo = min(lo5, lo0, round(sv_full))
    all_hi = max(hi5, hi0, round(sv_full))
    write_numbers_tex(all_lo, all_hi, errs)
    write_tables(errs)

    reseed = json.load(open(D / "reseed_std_protocol.json"))
    expect(f"spans ${reseed['spread_max_minus_min']}$ points" in TEX,
           f"reseed spread {reseed['spread_max_minus_min']} not in tex", errs)
    expect(f"SD ${reseed['sd']}$" in TEX, f"reseed sd {reseed['sd']} not in tex", errs)

    audit = json.load(open(ROOT / "docs/audit/recompute_final_50papers.json"))
    gaps = [abs(c["gap_points"]) for c in audit["comparisons"]]
    share = round(100 * sum(1 for g in gaps if g <= reseed["spread_max_minus_min"]) / len(gaps))
    expect(f"${share}\\%$" in TEX, f"gap-share {share}% not in tex", errs)
    lib = [c for c in audit["comparisons"] if c["benchmark"] in ("LIBERO", "LIBERO-Plus")]
    thr = reseed["spread_max_minus_min"]
    share_lib = round(100 * sum(1 for c in lib if abs(c["gap_points"]) <= thr) / len(lib))
    expect(f"${share_lib}\\%$" in TEX, f"LIBERO-family share {share_lib}% not in tex", errs)

    fr = sr[(1, 10)]
    expect(f"{fr:.3f}".lstrip("0") in TEX or f"{100*fr:.1f}\\%" in TEX,
           f"frontier SR {fr} not in tex", errs)
    fus = json.load(open(D / "fusion_shift.json"))
    cam2 = fus["per_axis"]["Camera Viewpoints"]["ns2"]["sr"]
    expect(f"{cam2:.3f}".lstrip("0") in TEX, f"s=2 camera {cam2} not in tex", errs)

    esr = json.load(open(D / "envseed_replication.json"))
    for es in ("8", "9"):
        t8 = esr["by_env_seed"][es]["libero_10/task8"]
        expect(f"${t8['e_pq_sampling']:.3f}$" in TEX,
               f"env-seed {es} task8 sampling component {t8['e_pq_sampling']:.3f} not in tex", errs)
        expect(f"${t8['mu']:.2f}$" in TEX,
               f"env-seed {es} task8 mu {t8['mu']:.2f} not in tex", errs)
        t0 = esr["by_env_seed"][es]["libero_10/task0"]
        expect(f"${t0['icc']:.2f}$" in TEX,
               f"env-seed {es} task0 icc {t0['icc']:.2f} not in tex", errs)

    sg = json.load(open(D / "smolvla_grid.json"))
    for cell, tex_fmt in (("nsdef_eh10", "$0.648$"), ("nsdef_eh5", "$0.596$")):
        sr = sg["cells"][cell]["sr"]
        expect(f"${sr:.3f}$" in TEX, f"smolvla grid {cell} sr {sr:.3f} not in tex", errs)
    e = sg["eh5_vs_eh10"]
    expect(f"${e['a_only']}$--${e['b_only']}$" in TEX or f"{e['b_only']}$--${e['a_only']}" in TEX,
           f"smolvla discordants {e['a_only']}/{e['b_only']} not in tex", errs)
    expect(f"p{{=}}{e['p']:.3f}" in TEX,
           f"smolvla grid mcnemar p {e['p']:.3f} not in tex", errs)
    eh1f = sg["cells"]["nsdef_eh1_full"]
    expect(f"${eh1f['sr']:.3f}$" in TEX, f"smolvla eh1 full sr {eh1f['sr']:.3f} not in tex", errs)
    e1cmp = sg["eh1_full_vs_eh10"]
    expect(f"[{e1cmp['diff_ci_pts'][0]*-1:.1f}".replace("-", "") in TEX or f"[{abs(e1cmp['diff_ci_pts'][1]):.1f}, {abs(e1cmp['diff_ci_pts'][0]):.1f}]" in TEX,
           "smolvla eh1 paired CI not in tex", errs)
    eh1t = sg["cells"]["nsdef_eh1"]
    expect(f"${eh1t['k']}/{eh1t['n']}$" in TEX, f"truncation exhibit {eh1t['k']}/{eh1t['n']} not in tex", errs)

    na = json.load(open(D / "new_axes.json"))["axes"]
    def pooled(axis, pol):
        cells = na[axis][pol].values()
        k = sum(c["k"] for c in cells); n = sum(c["n"] for c in cells)
        return k, n, k / n
    for axis in ("Light Conditions", "Robot Initial States"):
        for pol in ("pi05_libero", "pi0_libero"):
            _, _, sr = pooled(axis, pol)
            expect(f"${sr:.3f}$" in TEX, f"new-axes pooled {axis}/{pol} {sr:.3f} not in tex", errs)
    gr = abs(pooled("Robot Initial States", "pi05_libero")[2] - pooled("Robot Initial States", "pi0_libero")[2])
    expect(f"${100*gr:.1f}$" in TEX, f"ris gap {100*gr:.1f} not in tex", errs)

    dm = json.load(open(D / "decomp_minis.json"))
    for pol in ("pi0_libero", "smolvla_libero"):
        share = round(100 * (1 - dm[pol]["icc"]))
        expect(f"${share}\\%$" in TEX, f"decomp-mini sampling share {pol} {share}% not in tex", errs)
        expect(f"${dm[pol]['mu']:.2f}$" in TEX, f"decomp-mini mu {pol} {dm[pol]['mu']:.2f} not in tex", errs)

    fr1 = sg["cells"].get("ns1_eh10")
    if fr1:
        expect(f"${fr1['sr']:.3f}$" in TEX, f"smolvla frontier sr {fr1['sr']:.3f} not in tex", errs)
        dc = sg["def10_vs_ns1_10"]
        expect(f"${dc['diff_pts']}$" in TEX or f"${dc['diff_pts']:+.1f}".replace("+", "") in TEX
               or f"$-{abs(dc['diff_pts'])}$" in TEX,
               f"smolvla frontier diff {dc['diff_pts']} not in tex", errs)

    cpw = fus.get("camera_powerup")
    if cpw:
        expect(f"p{{=}}{cpw['mcnemar_p']:.3f}" in TEX, f"campow p {cpw['mcnemar_p']:.3f} not in tex", errs)
        expect("p{=}0.015" in TEX, "camera draw-1 per-axis p 0.015 not in tex", errs)
        expect(f"${cpw['pairs']}$ pairs, pooled $p{{=}}{cpw['mcnemar_p']:.3f}$" in TEX,
               f"exploratory pooled summary ({cpw['pairs']} pairs, p={cpw['mcnemar_p']:.3f}) not in tex", errs)
        expect(f"${cpw['pairs']}$" in TEX, f"campow pairs {cpw['pairs']} not in tex", errs)

    napw = json.load(open(D / "new_axes.json"))["pairwise"]
    inv = napw["Robot Initial States"]["pi0_libero_vs_smolvla_libero"]
    expect(inv["significant_inversion"], "RIS pi0-smolvla inversion no longer significant", errs)
    expect(f"${inv['a_only']}$--${inv['b_only']}$" in TEX or f"${inv['b_only']}$--${inv['a_only']}$" in TEX,
           f"inversion discordants {inv['b_only']}-{inv['a_only']} not in tex", errs)
    expect(f"p{{=}}{inv['p']:.4f}" in TEX, f"inversion p {inv['p']:.4f} not in tex", errs)
    smv = json.load(open(D / "new_axes.json"))["axes"]
    for axis, val in (("Light Conditions", None), ("Robot Initial States", None)):
        cells = smv[axis]["smolvla_libero"].values()
        sr = sum(c["k"] for c in cells) / sum(c["n"] for c in cells)
        expect(f"${sr:.3f}$" in TEX, f"smolvla pooled {axis} {sr:.3f} not in tex", errs)
    lc = napw["Light Conditions"]["pi0_libero_vs_smolvla_libero"]
    expect(f"${lc['a_only']}$--${lc['b_only']}$" in TEX,
           f"light pi0-smolvla discordants {lc['a_only']}-{lc['b_only']} not in tex", errs)

    pe = json.load(open(D / "pairing_efficiency.json"))
    effs = [v["rel_efficiency"] for v in pe.values()]
    span = f"${min(effs):.1f}$--${max(effs):.1f}"
    expect(span in TEX, f"pairing efficiency span {span} not in tex", errs)

    rt = json.load(open(D / "redteam_fixes.json"))
    if "v2_cluster_cis" in rt:
        ratios = []
        for key, cc in rt["v2_cluster_cis"].items():
            cp_w = cc["ci95_iid_cp"][1] - cc["ci95_iid_cp"][0]
            cl_w = cc["ci95_cluster_boot"][1] - cc["ci95_cluster_boot"][0]
            ratios.append(100 * (cl_w / cp_w - 1))
        wider = sum(1 for x in ratios if x > 0)
        ratios.sort()
        med = ratios[len(ratios)//2] if len(ratios) % 2 else (ratios[5] + ratios[6]) / 2
        expect(f"${wider}$ of ${len(ratios)}$" in TEX,
               f"bootstrap wider-count {wider}/{len(ratios)} not in tex", errs)
        expect(f"+{round(med)}\\%" in TEX, f"bootstrap median width {round(med)}% not in tex", errs)
        expect(f"+{round(max(ratios))}\\%" in TEX, f"bootstrap max width {round(max(ratios))}% not in tex", errs)
    v1t = json.load(open(D / "v1_varcomp_report.json"))["tasks"]
    n96 = sum(1 for t in v1t.values() if t["mu"] >= 0.96)
    expect(f"{('one two three four five six seven eight'.split())[n96-1]} of the eight battery tasks sit at" in TEX,
           f"battery >=0.96 count {n96} not worded in tex", errs)

    import statistics
    mdes = sorted(c["mde_points"] for c in audit["comparisons"] if c["mde_points"] is not None)
    med_mde = statistics.median(mdes)
    expect(f"${med_mde:g}$" in TEX, f"median per-comparison MDE {med_mde:g} not in tex", errs)

    cc2 = fus["camera_confirmatory"]
    expect(f"${cc2['sr_s1']:.3f}$" in TEX, f"camconf s1 {cc2['sr_s1']:.3f} not in tex", errs)
    expect(f"${cc2['sr_s10']:.3f}$" in TEX, f"camconf s10 {cc2['sr_s10']:.3f} not in tex", errs)
    expect(f"${cc2['s1_only']}$--${cc2['s10_only']}$" in TEX,
           f"camconf discordants {cc2['s1_only']}-{cc2['s10_only']} not in tex", errs)
    expect(f"p{{=}}{cc2['mcnemar_p']:.4f}" in TEX or f"p{{=}}0.0008" in TEX,
           f"camconf p not in tex", errs)
    expect(f"${cc2['pairs']}$" in TEX, f"camconf pairs {cc2['pairs']} not in tex", errs)
    dcc = round(100 * (cc2["sr_s10"] - cc2["sr_s1"]), 1)
    expect(f"${dcc}$-point" in TEX, f"camconf deficit {dcc} not in tex", errs)

    if errs:
        print("DRIFT DETECTED:")
        for e in errs:
            print(" -", e)
        return 1
    if "ANON-URL-PENDING" in TEX:
        print("WARNING: anonymized-mirror URL is still the placeholder; "
              "replace before PaperPlaza upload (docs/RELEASING.md).")
    print("all checked numbers consistent with data")
    return 0


if __name__ == "__main__":
    sys.exit(main())
